-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 12:03:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prueba1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba1` DEFAULT CHARACTER SET utf8 ;
USE `prueba1` ;

-- -----------------------------------------------------
-- Table `prueba1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`authors` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`modules` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `authors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `authors_id`),
  INDEX `fk_modules_authors1_idx` (`authors_id` ASC),
  CONSTRAINT `fk_modules_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `prueba1`.`authors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`theme` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `modules_id` INT NOT NULL,
  `modules_authors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `modules_id`, `modules_authors_id`),
  INDEX `fk_theme_modules1_idx` (`modules_id` ASC, `modules_authors_id` ASC),
  CONSTRAINT `fk_theme_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `prueba1`.`modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`tests` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `theme_id` INT NOT NULL,
  `theme_modules_id` INT NOT NULL,
  `theme_modules_authors_id` INT NOT NULL,
  `authors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `theme_id`, `theme_modules_id`, `theme_modules_authors_id`, `authors_id`),
  INDEX `fk_tests_theme1_idx` (`theme_id` ASC, `theme_modules_id` ASC, `theme_modules_authors_id` ASC),
  INDEX `fk_tests_authors1_idx` (`authors_id` ASC),
  CONSTRAINT `fk_tests_theme1`
    FOREIGN KEY (`theme_id` , `theme_modules_id` , `theme_modules_authors_id`)
    REFERENCES `prueba1`.`theme` (`id` , `modules_id` , `modules_authors_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `prueba1`.`authors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`questions` (
  `id` INT NULL AUTO_INCREMENT,
  `pregunta` TEXT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `respuesta` TEXT NOT NULL,
  `opciones` TEXT NOT NULL,
  `tests_id` INT NOT NULL,
  `tests_theme_id` INT NOT NULL,
  `tests_theme_modules_id` INT NOT NULL,
  `tests_theme_modules_authors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tests_id`, `tests_theme_id`, `tests_theme_modules_id`, `tests_theme_modules_authors_id`),
  INDEX `fk_questions_tests1_idx` (`tests_id` ASC, `tests_theme_id` ASC, `tests_theme_modules_id` ASC, `tests_theme_modules_authors_id` ASC),
  CONSTRAINT `fk_questions_tests1`
    FOREIGN KEY (`tests_id` , `tests_theme_id` , `tests_theme_modules_id` , `tests_theme_modules_authors_id`)
    REFERENCES `prueba1`.`tests` (`id` , `theme_id` , `theme_modules_id` , `theme_modules_authors_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba1`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba1`.`results` (
  `id` INT NULL AUTO_INCREMENT,
  `puntuacion` INT NOT NULL,
  `fecha_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  `tests_theme_id` INT NOT NULL,
  `tests_theme_modules_id` INT NOT NULL,
  `tests_theme_modules_authors_id` INT NOT NULL,
  `tests_authors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `tests_id`, `tests_theme_id`, `tests_theme_modules_id`, `tests_theme_modules_authors_id`, `tests_authors_id`),
  INDEX `fk_results_users1_idx` (`users_id` ASC),
  INDEX `fk_results_tests1_idx` (`tests_id` ASC, `tests_theme_id` ASC, `tests_theme_modules_id` ASC, `tests_theme_modules_authors_id` ASC, `tests_authors_id` ASC),
  CONSTRAINT `fk_results_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `prueba1`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_tests1`
    FOREIGN KEY (`tests_id` , `tests_theme_id` , `tests_theme_modules_id` , `tests_theme_modules_authors_id` , `tests_authors_id`)
    REFERENCES `prueba1`.`tests` (`id` , `theme_id` , `theme_modules_id` , `theme_modules_authors_id` , `authors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
